import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="flex items-center uppercase text-sm">
            {" "}
            <img src="/tayibah-logo.jpg" className="w-52" />
            <div className="ml-auto flex mr-10">
              <a className="pr-5 cursor-pointer hover:text-black" href="#about">
                About
              </a>
              <a
                className="pr-5 cursor-pointer hover:text-black"
                href="#gallery"
              >
                Gallery
              </a>
              <a
                className="pr-5 cursor-pointe hover:text-black"
                href="#contact"
              >
                Contact
              </a>
            </div>
          </div>
        </nav>
        {children}
        <footer className="w-full bg-gray-200">
          <p className="p-20 uppercase text-sm">Tayibah farms 2024</p>
        </footer>
      </body>
    </html>
  );
}
